### ISSUE TITLE
We are now an Organization

### ISSUE THREAD

**Issue by FunnyBuddys** [NewTesseractTeam/NewTesseract#1]
We are now an Organization and search members!

**Comment by NFGamerMC** [comment]
I can code great, I was a Tesseract own until Linux look over.

**Comment by jdongel2004** [comment]
Nice! Can I join Develops..?

**Comment by FunnyBuddys** [comment]
I invite Both of you

**Comment by NFGamerMC** [comment]
I need to be owner t9 setup CI

**Comment by FunnyBuddys** [comment]
I setup CI but Thanks.

**Comment by jdongel2004** [comment]
Come back?

**Comment by BexiPE** [comment]
I can join it to Develop lol
