### ISSUE TITLE
저기 콘피그를 json말고 .txt로 바꾸어주시면 안되나요?

### ISSUE THREAD

**Issue by shdudwns** [NewTesseractTeam/NewTesseract#10]
Can not you change the konfig to .txt instead of json?
@jdongel2004

**Comment by shdudwns** [comment]
@FunnyBuddys

**Comment by jdongel2004** [comment]
무슨 콘피그요?

**Comment by BexiPE** [comment]
@shdudwns What do you mean? the config is a YAML.

**Comment by jdongel2004** [comment]
He means when he start, and stop. op.json , whitelist.json ...

**Comment by FunnyBuddys** [comment]
Why you need txt?
