### ISSUE TITLE
I can not access the game. It keeps time out.

### ISSUE THREAD

**Issue by shdudwns** [NewTesseractTeam/NewTesseract#11]
I can not access the game. It keeps time out.(게임이 접속 안됩니다. time out이라뜹니다)

**Comment by jdongel2004** [comment]
월드 삭제 / 플러그인 모두 삭제 후 재시도해보세요. Plz delete the world and plugins and try.

**Comment by FunnyBuddys** [comment]
Need more infos

**Comment by shdudwns** [comment]
@FunnyBuddys Why closed??

**Comment by shdudwns** [comment]
It is error
