### ISSUE TITLE
Still getting Disconnected from server..

### ISSUE THREAD

**Issue by ObeyBeastJj23** [NewTesseractTeam/NewTesseract#3]
#### Problem description

Disconnect on join and never loading still..

#### Steps to reproduce the issue

Run latest Master, join server and wait to be disconnected

#### OS and versions

* Tesseract: Tesseract-1.3.0 Revolution
* PHP: 7.0.3
* Server OS: Idk
* Game version: 1.1.0.55/Latest
* Server host: Scalacube
<br><br>
#### Crashdump, backtrace, memory dumps, plugins list or other files

http://imgur.com/o0hjDd4
http://imgur.com/mcCy3ZG

**Comment by jdongel2004** [comment]
Suddenly, the game shut down?

**Comment by ObeyBeastJj23** [comment]
No no no.. it just disconnects you, I'll edit this and add screen shots

**Comment by jdongel2004** [comment]
Hmm.. I'll check..

**Comment by opkiler22789** [comment]
+1
